name: Build on Ubuntu 20.04

on:
  push:
    branches:
      - main
      - v*

    paths:
      - cmake/**
      - src/**
      - CMakeLists.txt

  pull_request:
    paths:
      - cmake/**
      - src/**
      - CMakeLists.txt

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            tzdata \
            build-essential \
            cmake \
            git \
            libboost-all-dev \
            libssl-dev \
            libmysqlclient-dev \
            lua5.1-dev \
            liblua5.3-dev \
            libpugixml-dev \
            libcrypto++-dev \
            liblua5.3-0 \
            libfmt-dev \
            libgmp-dev \
            && sudo apt-get clean

      - name: Build with cmake
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          # will set the CC & CXX for cmake
          cc: gcc
          cxx: g++
          build-type: Release
          # Extra options pass to cmake while configuring project
          configure-options: -DUSE_LUAJIT=on
          # run build using '-j [parallel]' to use multiple threads to build
          parallel: 2

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-tfs-amd64-${{ github.sha }}
          path: ${{ runner.workspace }}/build/tfs
