name: Build on Ubuntu Arm64

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*

    paths:
      - cmake/**
      - src/**
      - CMakeLists.txt
    pull_request:
     branches:
      - main


  pull_request:
    paths:
      - cmake/**
      - src/**
      - CMakeLists.txt

jobs:
  build-ubuntu:
    runs-on: self-hosted
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            tzdata \
            build-essential \
            cmake \
            git \
            libboost-dev \
            libboost-system-dev \
            libboost-filesystem-dev \
            libssl-dev \
            libmysqlclient-dev \
            lua5.3-dev \
            liblua5.3-dev \
            libpugixml-dev \
            libcrypto++-dev \
            liblua5.3-0 \
            libfmt-dev \
            libgmpxx4ldbl=2:6.2.1+dfsg-3ubuntu1 \
            && sudo apt-get clean

      - name: Build with cmake
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          # will set the CC & CXX for cmakee
          cc: gcc
          cxx: g++
          build-type: Release
          # Extra options pass to cmake while configuring project
          configure-options: -DUSE_LUAJIT=off
          # run build using '-j [parallel]' to use multiple threads to build
          parallel: 2

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-tfs-amd64-${{ github.sha }}
          path: ${{ runner.workspace }}/build/tfs
